django_src/detection_app/urls.py
"""Defines URL patterns for emotion_detection"""

from django.urls import path

from . import views


app_name = "detection_app"

urlpatterns = [path("", views.home, name="home")]

django_src/emotion_detection/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("detection_app.urls")),
]

django_src/detection_app/models.py
from django.db import models

# Create your models here.


class PromptModel(models.Model):
    prompt = models.CharField(max_length=2000, blank=False, null=False)
    answer = models.CharField(max_length=100, blank=False, null=False)

    def __str__(self):
        return f"prompt:\n{self.prompt}\nanswer: {self.answer}\n"

    class Meta:
        db_table = "prompt_history"

django_src/detection_app/views.py
from django.shortcuts import render

from ollama import generate

from .models import PromptModel


# ------------------------------------------------ #
# --------------- helper functions --------------- #
# ------------------------------------------------ #
def get_answer_from_model(text: str):
    """
    Prompt the model and get the answer as output.
    """
    # for gemma
    prompt = f"""Analyze the emotion of the text enclosed in square brackets,
determine if it is Happy, Love, Sadness, Anger or Fear, and return the answer only as
the corresponding sentiment label 'Happy' or 'Love' or 'Sadness' or 'Anger' or 'Fear'

[{text}] = """.strip()

    response = generate(
        model="emotion_analysis_gemma_2b__v3.4.0",
        prompt=prompt,
        # response will be recieved in a single reply
        stream=False,
        options={
            # max new token count
            "num_predict": 2,
            # controls creativity when generating
            # temperature = 0 means the response is reproducible
            "temperature": 0,
        },
    )

    return response["response"]


def get_history():
    """
    Get the history of all prompts with response.
    """
    return PromptModel.objects.all()


# ------------------------------------- #
# --------------- views --------------- #
# ------------------------------------- #
def home(request):
    # create a dictionary to send data for rendering in the template
    context = {}
    # get history of all prompts with response from database
    history = get_history()

    if request.method == "POST":
        # get prompt from user
        prompt = request.POST["prompt"]
        # generate response for the user prompt
        answer = get_answer_from_model(prompt)

        # store the user prompt along with the response in the database
        prompt_answer = PromptModel(prompt=prompt, answer=answer)
        prompt_answer.save()

    # insert history inside dictionary to send it to the template
    context["history"] = history

    return render(request, "detection_app/home.html", context)

django_src/detection_app/templates/detection_app/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  {% load static %}
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap-icons/font/bootstrap-icons.css' %}">

  <style>
    ::-webkit-scrollbar {
      width: 8px;
      padding-left: 20px;
    }

    ::-webkit-scrollbar-track {
      border-radius: 20px;
    }

    ::-webkit-scrollbar-thumb {
      background-color: #383838;
      border-radius: 20px;
    }

    .self_nav {
      background-color: #323131 !important;
    }

    .self_history_container {
      background-color: #232424 !important;
      display: flex;
      flex-direction: column;
      height: 88vh;
    }

    .self_history {
      flex: 1;
      overflow-y: auto;
    }

    .self_history_prompt {
      background-color: #2F3030 !important;
    }

    .self_history_response {
      background-color: #232424 !important;
    }

    .self_input {
      background-color: #323131 !important;
      border: 0px !important;
    }
    .self_input:focus {
      box-shadow: 0px 0px 0px rgba(0, 0, 0, 0.075) inset, 0px 0px 0px rgba(50, 49, 49, 0.5) !important;
    }

    .self_button {
      background-color: #676767 !important;
      border: 0px !important;
    }
  </style>

  {% block title %}{% endblock title %}

</head>

<body class="self_history_response" data-bs-theme="dark">
  <nav class="self_nav navbar sticky-top">
    <div class="container-fluid">
      <a class="ms-2 navbar-brand" href="">
        <!-- <i class="bi bi-emoji-smile-fill"></i> -->
        <strong>Bangla Emotion Analysis With Gemma-2b</strong>
      </a>
    </div>
  </nav>

  <div class="self_history_container container px-5 mt-4">

    {% block content %}{% endblock content %}

  </div>

  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  <script>
    document.addEventListener('DOMContentLoaded', function() {
      var chatHistory = document.getElementById('history');
      chatHistory.scrollTop = chatHistory.scrollHeight;
    });
  </script>
</body>
</html>

django_src/detection_app/templates/detection_app/home.html
{% extends 'detection_app/base.html' %}

{% block title %}
  <title>Emotion Detection</title>
{% endblock title %}

{% block content %}
  <!-- prompt history -->
  <div class="self_history mb-2 p-4 rounded-5" id="history">
    {% for item in history %}
      <div class="fs-5 my-4">
        <div class="self_history_prompt d-grid gap-2 col-6 ms-auto rounded-4">
          <div class="text-wrap px-3 py-1">
            {{ item.prompt }}
          </div>
        </div>

        <div class="d-flex align-items-center my-4">
          <div>
            <i class="border rounded-pill px-2 py-1 bi bi-emoji-smile-fill"></i>
          </div>

          <div class="self_history_response d-grid gap-2 col-3 rounded-4">
            <div class="text-wrap px-4 py-1">
              Emotion: {{ item.answer }}
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>

  <!-- prompt input -->
  <div class="mb-4">
    <form action="{% url 'detection_app:home' %}" method="post">
      {% csrf_token %}

        <div class="self_input input-group p-2 rounded-pill">
          <input class="self_input form-control form-control-lg px-4 border-0 rounded-pill" name="prompt" placeholder="Enter your message..." required></input>
          <button type="submit" class="self_button btn btn-primary btn-lg ms-2 rounded-pill"><i class="bi bi-arrow-up-circle-fill"></i></button>
        </div>

      </div>
    </form>
  </div>


{% endblock content %}